apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-server
  labels:
    app: web
    chrome-operator-reload: "true"
  annotations:
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: k8s-web-server
          image: k8s-web-server
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: FED_MODULES
              valueFrom:
                configMapKeyRef:
                  name: chrome-config-map
                  key: fed-modules
