//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeDynamicUI) DeepCopyInto(out *ChromeDynamicUI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeDynamicUI.
func (in *ChromeDynamicUI) DeepCopy() *ChromeDynamicUI {
	if in == nil {
		return nil
	}
	out := new(ChromeDynamicUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChromeDynamicUI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeDynamicUIList) DeepCopyInto(out *ChromeDynamicUIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChromeDynamicUI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeDynamicUIList.
func (in *ChromeDynamicUIList) DeepCopy() *ChromeDynamicUIList {
	if in == nil {
		return nil
	}
	out := new(ChromeDynamicUIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChromeDynamicUIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeDynamicUISpec) DeepCopyInto(out *ChromeDynamicUISpec) {
	*out = *in
	in.Module.DeepCopyInto(&out.Module)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeDynamicUISpec.
func (in *ChromeDynamicUISpec) DeepCopy() *ChromeDynamicUISpec {
	if in == nil {
		return nil
	}
	out := new(ChromeDynamicUISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeDynamicUIStatus) DeepCopyInto(out *ChromeDynamicUIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeDynamicUIStatus.
func (in *ChromeDynamicUIStatus) DeepCopy() *ChromeDynamicUIStatus {
	if in == nil {
		return nil
	}
	out := new(ChromeDynamicUIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeUIModules) DeepCopyInto(out *ChromeUIModules) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeUIModules.
func (in *ChromeUIModules) DeepCopy() *ChromeUIModules {
	if in == nil {
		return nil
	}
	out := new(ChromeUIModules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChromeUIModules) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeUIModulesList) DeepCopyInto(out *ChromeUIModulesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChromeUIModules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeUIModulesList.
func (in *ChromeUIModulesList) DeepCopy() *ChromeUIModulesList {
	if in == nil {
		return nil
	}
	out := new(ChromeUIModulesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChromeUIModulesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeUIModulesSpec) DeepCopyInto(out *ChromeUIModulesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeUIModulesSpec.
func (in *ChromeUIModulesSpec) DeepCopy() *ChromeUIModulesSpec {
	if in == nil {
		return nil
	}
	out := new(ChromeUIModulesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChromeUIModulesStatus) DeepCopyInto(out *ChromeUIModulesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChromeUIModulesStatus.
func (in *ChromeUIModulesStatus) DeepCopy() *ChromeUIModulesStatus {
	if in == nil {
		return nil
	}
	out := new(ChromeUIModulesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteDefinition) DeepCopyInto(out *RouteDefinition) {
	*out = *in
	if in.Props != nil {
		in, out := &in.Props, &out.Props
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteDefinition.
func (in *RouteDefinition) DeepCopy() *RouteDefinition {
	if in == nil {
		return nil
	}
	out := new(RouteDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UiModule) DeepCopyInto(out *UiModule) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UiModule.
func (in *UiModule) DeepCopy() *UiModule {
	if in == nil {
		return nil
	}
	out := new(UiModule)
	in.DeepCopyInto(out)
	return out
}
