# permissions for end users to edit chromedynamicuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: chromedynamicui-editor-role
rules:
- apiGroups:
  - martin.com
  resources:
  - chromedynamicuis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - martin.com
  resources:
  - chromedynamicuis/status
  verbs:
  - get
