# permissions for end users to view chromeuimodules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: chromeuimodules-viewer-role
rules:
- apiGroups:
  - martin.com
  resources:
  - chromeuimodules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - martin.com
  resources:
  - chromeuimodules/status
  verbs:
  - get
