# permissions for end users to view chromedynamicuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: chromedynamicui-viewer-role
rules:
- apiGroups:
  - martin.com
  resources:
  - chromedynamicuis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - martin.com
  resources:
  - chromedynamicuis/status
  verbs:
  - get
