---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - martin.com
  resources:
  - chromeuimodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - martin.com
  resources:
  - chromeuimodules/finalizers
  verbs:
  - update
- apiGroups:
  - martin.com
  resources:
  - chromeuimodules/status
  verbs:
  - get
  - patch
  - update
