apiVersion: martin.com/v1alpha1
kind: ChromeDynamicUI
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: ui-module-2
spec:
  name: ui-module-2
  title: "UI Module 2"
  module:
    manifestLocation: "/apps/ui-module-2/fed-mods.json"
    routes:
    - pathname: "/foo/bar/baz"
      exact: true
      module: "./RootApp"
      props:
        input: value
        foo: bar
